### PR TITLE
Go back to use_controller_vm

### PR DESCRIPTION
**Pull request by benrudolph**

### CODE REVIEW

**Comment by snopoke** [comment]
how come?

**Comment by benrudolph** [comment]
it's unclear to me what's happening when i don't use `use_controller_vm`. My understanding is that when I specify localhost, without `use_controller_vm`, tsung will start a remote beam and will ssh into localhost (kind of weird) and then start a VM to run the requests. i thought `use_controller_vm` just starts a VM on localhost and sends the requests. i was having trouble setting it up without `use_controller_vm` since you have to have passwordless ssh, which in itself is not a problem, but i can't figure out what user tsung is using to ssh into the client machine. i tried putting authorized keys for user `cchq` but that still didn't work.

if you know more about let me know, these docs left a lot missing for me: http://tsung.erlang-projects.org/user_manual/conf-client-server.html

**Comment by benrudolph** [comment]
the reason i initially removed `use_controller_vm` was that tsung was stopping because we'd hit too many users. this is why we'd error out on 250 users/sec. it was not because postgres was falling over. i thought that we could have unlimited users if we didn't `use_controller_vm` but i'm pretty sure i'm conflating something

**Comment by benrudolph** [comment]
one other thing, the errors we get when i bump up to 200 users/sec:

```
PGSQL: Got Error Msg from postgresql [[{severity,
                                                                            'FATAL'},
                                                                           {code,
                                                                            "53300"},
                                                                           {message,
                                                                            "sorry, too many clients already"},
                                                                           {file,
                                                                            "proc.c"},
                                                                           {line,
                                                                            339},
                                                                           {routine,
```

my intuition was that that would be resolved with `pgbouncer`. do you suspect something else?

**Comment by snopoke** [comment]
I think there are 2 possible solutions. Either change the postgres cooing
to allow more users (assuming it's set to 200) or set up pgbouncer.

I think the pgbouncer route makes more sense since it will better replicate
how we'll run it for real. Also it should reduce the memory overhead for
postgres since pg allocates memory for every connection.

**Comment by snopoke** [comment]
I don't know about the VM thing.

**Pull request merged**
